In [1]:
print("Hello World !")

Hello World !

In [2]:
! pip install pandas

Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
# pandas --> pandas it

In [4]:
import pandas as pd

In [5]:
# Data Structure of pandas-->
# (1). Series --> it stores only values not column and it is one dimantional 
# (2). Dataframe -->it st

In [6]:
a =pd.Series([1,45,78,90])

In [7]:
print(type(a))

<class 'pandas.Series'>

In [8]:
# DataFrame

In [9]:
a ={
    'Emp_id' : [1,2,3,4,5],
    'Name' : ['sam','Mohit','Raj','Rahuel','Ankiet'],
    "Department" : ['it','sales','it','it','sales'],
    "Salary" : [20000,25000,30000,31000,26000]
}

In [10]:
df = pd.DataFrame(a)
df

   Emp_id    Name Department  Salary
0       1     sam         it   20000
1       2   Mohit      sales   25000
2       3     Raj         it   30000
3       4  Rahuel         it   31000
4       5  Ankiet      sales   26000

In [11]:
# Export Data into csv

In [12]:
df.to_csv("Emp_data.csv")

In [13]:
# Export Data into Exel

In [24]:
# df.to_excel("New_Emp_Data.xlsx")

In [15]:
# Import the data

In [16]:
a =pd.read_csv("C:\\Users\\HP\\OneDrive\\Desktop\\Python_Regex\\Pandas\\pandas\\phones_data.csv")
a.head(1)

,k7wcnx href,UCc1lI src,fU6cHR,RG5Slk,MKiFS6,PZfbSE src,PvbNMB,o2SIOJ,PvbNMB 2,DTBslk,...,DTBslk 5,DTBslk 6,hZ3P6w,kRYCnD,HQe8jr,qYp2rh src,HZ0E6r,HZ0E6r 2,HZ0E6r 3,HZ0E6r 4
0,https://www.flipkart.com/google-pixel-9a-porce...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"Google Pixel 9A (Porcelain, 256 GB)",4.5,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...","8,289 Ratings",&,548 Reviews,8 GB RAM | 256 GB ROM,...,Tensor G4 Processor,1 Year Domestic Warranty,"₹39,999","₹49,999",20% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹32,900",Off on Exchange,Bank Offer

In [19]:
a =pd.read_csv("C:\\Users\\HP\\OneDrive\\Desktop\\Python_Regex\\Pandas\\pandas\\Emp_data.csv")
a.head(5)

   Unnamed: 0  Emp_id    Name Department  Salary
0           0       1     sam         it   20000
1           1       2   Mohit      sales   25000
2           2       3     Raj         it   30000
3           3       4  Rahuel         it   31000
4           4       5  Ankiet      sales   26000