In [1]:
print("Day 2")

Day 2

In [2]:
import pandas as pd

In [3]:
# student_id , course , course_duration , total_fees

In [ ]:
# Student_ID,  Name , Course_Name , Course_Duration , total_fees --> 10 rows
# these are the column names 
# you have to create a dataframe with having 10 rows
# export this dataframe into csv and excel
# then these 2 datsets , you have to create a new repository ('data_students") and upload 2 datasets on this github repo

In [16]:
a ={
    'Student_id' : [1,2,3,4,5,6,7,8,9,10],
    'Name' : ['Ankit','Aman','KaluRam','Chetan','Ankiet','Dev','Sunil','Ram','Laxy','Rahul'],
    "Course_Duration" : [3,4,5,6,7,8,9,10,10,12],
    "Total_Fess" : [300000,125000,230000,131000,126000,1220000,125000,130000,131000,126000]
}

In [19]:
d = pd.DataFrame(a)
d

   Student_id     Name  Course_Duration  Total_Fess
0           1    Ankit                3      300000
1           2     Aman                4      125000
2           3  KaluRam                5      230000
3           4   Chetan                6      131000
4           5   Ankiet                7      126000
5           6      Dev                8     1220000
6           7    Sunil                9      125000
7           8      Ram               10      130000
8           9     Laxy               10      131000
9          10    Rahul               12      126000

In [ ]:
! pip install openpyxl # Install the Library

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [38]:
d.to_csv("Student_Data.csv")
d.to_excel("Student_Data2.xlsx")

In [39]:
a = pd.read_csv("C:\\Users\\HP\\OneDrive\\Desktop\\Python_Regex\\Pandas\\pandas\\Hotes.csv")
a.head(4)

,BMQDV href,NhWcC src,biGQs,biGQs 2,evwcZ,BMQDV href 3,biGQs 3,AVYYu,AVYYu 2,AVYYu 3,AVYYu 4,BMQDV href 4,TPuys src
0,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,1. Jaypee Residency Manor,4.7,4.7 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,"(3,137 reviews)",Romantic,Park View,Classic,Breakfast included,NaN,NaN
1,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,2. Hotel Vishnu Palace,4.5,4.5 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,"(3,353 reviews)",Family,Modern,Business,Breakfast included,https://www.tripadvisor.in/Hotel_Review-g29768...,https://static.tacdn.com/img2/brand_refresh_20...
2,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,"3. Country Inn Premier Pacific Resort, Mussoorie",4.4,4.4 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,(297 reviews),Romantic,Trendy,Business,NaN,https://www.tripadvisor.in/Hotel_Review-g29768...,https://static.tacdn.com/img2/brand_refresh_20...
3,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,4. Pride Ashiyana Resort Mussoorie,4.9,4.9 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,(795 reviews),Romantic,Family,Quaint,Breakfast included,https://www.tripadvisor.in/Hotel_Review-g29768...,https://static.tacdn.com/img2/brand_refresh_20...