In [89]:
print("Day3")

Day3

In [90]:
import numpy as np
import pandas as pd

In [91]:
df = pd.read_csv("C:\\Users\\HP\\OneDrive\\Desktop\\Python_Regex\\Pandas\\pandas\\placement.csv")
df

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [92]:
df.head() # By default 5

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [93]:
df.tail()

    cgpa  resume_score  placed
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [94]:
df.describe() # Staticaly view of data

           cgpa  resume_score      placed
count  100.0000    100.000000  100.000000
mean     6.9422      6.930500    0.500000
std      1.1192      0.979608    0.502519
min      5.2700      4.950000    0.000000
25%      5.9800      6.190000    0.000000
50%      6.6200      7.055000    0.500000
75%      8.0450      7.640000    1.000000
max      9.4000      9.060000    1.000000

In [95]:
df.info() # it will return's the overall details of the data (Data Type Information)

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [96]:
top_left_corner_df = df.iloc[:4,:3] # iloc[row_range ,columns_range]
top_left_corner_df

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1

In [97]:
df.loc[1:3 , ['cgpa' , 'placed']] # loc[row_range , column_name]

   cgpa  placed
1  6.17       0
2  8.27       1
3  6.88       1

In [98]:
s = df.axes 
s

[RangeIndex(start=0, stop=100, step=1),
 Index(['cgpa', 'resume_score', 'placed'], dtype='str')]

In [99]:
p = df.dtypes # To Check The Data Types of the data in the files 
p

cgpa            float64
resume_score    float64
placed            int64
dtype: object

In [100]:
df['cgpa'].dtypes

dtype('float64')

In [101]:
b =df.empty ##it returns true if there any missing data in dataframe otherwise returns False
b

False

In [102]:
df.isnull().sum()  #  For Check Missing Values

cgpa            0
resume_score    0
placed          0
dtype: int64

In [103]:
df = df.dropna() # For Remove Missing Row

In [104]:
i = df.ndim # NUmber Of Axes (it is 2)
i

2

In [105]:
t =df.shape # shape = n(rows) , n(columns)
t
df.shape[0] # Total Rows in Data
df.shape[1] # Total Columns in Data

3

In [106]:
d =df.size # Row Count * Columns Count
d

300

In [107]:
a = df.values # Get A NumPy Arrary For DataFrame
a

array([[8.14, 6.52, 1.  ],
       [6.17, 5.17, 0.  ],
       [8.27, 8.86, 1.  ],
       [6.88, 7.27, 1.  ],
       [7.52, 7.3 , 1.  ],
       [8.77, 6.19, 1.  ],
       [5.34, 7.09, 0.  ],
       [6.56, 6.29, 0.  ],
       [6.32, 6.71, 0.  ],
       [7.69, 7.12, 1.  ],
       [6.18, 6.35, 0.  ],
       [5.44, 6.54, 0.  ],
       [6.09, 7.01, 0.  ],
       [8.5 , 5.09, 1.  ],
       [7.51, 6.25, 1.  ],
       [8.88, 5.93, 1.  ],
       [8.04, 7.64, 1.  ],
       [7.81, 8.71, 1.  ],
       [5.94, 5.88, 0.  ],
       [6.75, 8.11, 1.  ],
       [5.8 , 8.06, 0.  ],
       [6.53, 7.64, 0.  ],
       [6.16, 5.77, 0.  ],
       [6.05, 7.13, 0.  ],
       [8.22, 6.18, 1.  ],
       [7.76, 5.68, 1.  ],
       [6.27, 6.47, 0.  ],
       [5.51, 6.15, 0.  ],
       [7.46, 7.67, 1.  ],
       [6.19, 7.3 , 0.  ],
       [7.36, 7.15, 1.  ],
       [5.92, 7.02, 0.  ],
       [5.87, 7.96, 0.  ],
       [8.43, 7.73, 1.  ],
       [8.87, 7.19, 1.  ],
       [8.07, 7.48, 1.  ],
       [8.16, 7.56, 1.  ],
       [9.05, 8.21, 1.  ],
       [6.  , 8.72, 0.  ],
       [7.5 , 6.19, 1.  ],
       [8.25, 5.32, 1.  ],
       [8.68, 5.15, 1.  ],
       [6.9 , 6.91, 1.  ],
       [8.21, 7.95, 1.  ],
       [5.47, 5.92, 0.  ],
       [8.1 , 5.44, 1.  ],
       [5.83, 5.21, 0.  ],
       [7.05, 8.14, 1.  ],
       [5.54, 6.57, 0.  ],
       [5.46, 6.73, 0.  ],
       [8.22, 6.74, 1.  ],
       [6.54, 7.39, 0.  ],
       [5.9 , 7.5 , 0.  ],
       [6.  , 7.16, 0.  ],
       [5.92, 7.18, 0.  ],
       [6.94, 6.87, 1.  ],
       [6.13, 6.43, 0.  ],
       [6.34, 7.21, 0.  ],
       [6.47, 7.37, 0.  ],
       [5.95, 7.57, 0.  ],
       [5.87, 6.64, 0.  ],
       [6.89, 7.96, 1.  ],
       [5.75, 8.43, 0.  ],
       [8.65, 7.58, 1.  ],
       [7.93, 8.09, 1.  ],
       [6.04, 8.75, 0.  ],
       [8.35, 8.02, 1.  ],
       [6.59, 6.81, 1.  ],
       [6.01, 7.49, 0.  ],
       [8.06, 9.06, 1.  ],
       [7.12, 7.41, 1.  ],
       [7.34, 8.22, 1.  ],
       [7.63, 7.98, 1.  ],
       [5.76, 6.48, 0.  ],
       [5.54, 7.36, 0.  ],
       [6.34, 7.94, 1.  ],
       [9.4 , 5.5 , 1.  ],
       [5.88, 6.92, 0.  ],
       [5.79, 5.66, 0.  ],
       [5.27, 7.28, 0.  ],
       [7.83, 7.7 , 1.  ],
       [6.12, 6.72, 0.  ],
       [7.92, 6.06, 1.  ],
       [7.6 , 8.08, 1.  ],
       [5.76, 6.49, 0.  ],
       [6.72, 5.46, 0.  ],
       [6.18, 5.76, 0.  ],
       [5.62, 5.05, 0.  ],
       [8.07, 6.07, 1.  ],
       [5.99, 7.49, 0.  ],
       [5.85, 5.56, 0.  ],
       [8.28, 6.3 , 1.  ],
       [5.43, 6.18, 0.  ],
       [9.31, 7.39, 1.  ],
       [8.01, 4.95, 1.  ],
       [6.33, 6.38, 0.  ],
       [8.23, 7.76, 1.  ],
       [6.65, 7.78, 0.  ],
       [8.14, 5.63, 1.  ],
       [6.09, 6.61, 0.  ]])

In [108]:
df = df.copy
df

<bound method NDFrame.copy of     cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]>

In [109]:
p = df().sort_values(by = 'resume_score')
p

    cgpa  resume_score  placed
94  8.01          4.95       1
87  5.62          5.05       0
13  8.50          5.09       1
41  8.68          5.15       1
1   6.17          5.17       0
..   ...           ...     ...
17  7.81          8.71       1
38  6.00          8.72       0
65  6.04          8.75       0
2   8.27          8.86       1
69  8.06          9.06       1

[100 rows x 3 columns]

In [110]:
### Tips Data Set -->
# categorical column --_. Numerical Column convert Usign Map 
# rows , columns , loc , iloc , 1 column sort

In [118]:
df = pd.read_csv("C:\\Users\\HP\\OneDrive\\Desktop\\Python_Regex\\Pandas\\pandas\\tips.csv")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [119]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [122]:
df['sex'] = df['sex'].map({'female':0,'male':1})
df

     total_bill   tip  sex smoker   day    time  size
0         16.99  1.01  NaN     No   Sun  Dinner     2
1         10.34  1.66  NaN     No   Sun  Dinner     3
2         21.01  3.50  NaN     No   Sun  Dinner     3
3         23.68  3.31  NaN     No   Sun  Dinner     2
4         24.59  3.61  NaN     No   Sun  Dinner     4
..          ...   ...  ...    ...   ...     ...   ...
239       29.03  5.92  NaN     No   Sat  Dinner     3
240       27.18  2.00  NaN    Yes   Sat  Dinner     2
241       22.67  2.00  NaN    Yes   Sat  Dinner     2
242       17.82  1.75  NaN     No   Sat  Dinner     2
243       18.78  3.00  NaN     No  Thur  Dinner     2

[244 rows x 7 columns]

In [123]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [124]:
df['day'] = df['day'].map({'sat':1,'sun':2,'thur':3,'Fri':4})
df

     total_bill   tip  sex smoker  day    time  size
0         16.99  1.01  NaN     No  NaN  Dinner     2
1         10.34  1.66  NaN     No  NaN  Dinner     3
2         21.01  3.50  NaN     No  NaN  Dinner     3
3         23.68  3.31  NaN     No  NaN  Dinner     2
4         24.59  3.61  NaN     No  NaN  Dinner     4
..          ...   ...  ...    ...  ...     ...   ...
239       29.03  5.92  NaN     No  NaN  Dinner     3
240       27.18  2.00  NaN    Yes  NaN  Dinner     2
241       22.67  2.00  NaN    Yes  NaN  Dinner     2
242       17.82  1.75  NaN     No  NaN  Dinner     2
243       18.78  3.00  NaN     No  NaN  Dinner     2

[244 rows x 7 columns]

In [125]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [126]:
df.shape

(244, 7)

In [128]:
df.shape[0]

244

In [129]:
df.shape[1]

7

In [130]:
df.iloc[:3,:4]

   total_bill   tip  sex smoker
0       16.99  1.01  NaN     No
1       10.34  1.66  NaN     No
2       21.01  3.50  NaN     No

In [133]:
df.loc[2:3,['total_bill','smoker']]

   total_bill smoker
2       21.01     No
3       23.68     No