In [1]:
print("Pandas Revision")

Pandas Revision

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("Hotes.csv")

In [4]:
df

,BMQDV href,NhWcC src,biGQs,biGQs 2,evwcZ,BMQDV href 3,biGQs 3,AVYYu,AVYYu 2,AVYYu 3,AVYYu 4,BMQDV href 4,TPuys src
0,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,1. Jaypee Residency Manor,4.7,4.7 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,"(3,137 reviews)",Romantic,Park View,Classic,Breakfast included,NaN,NaN
1,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,2. Hotel Vishnu Palace,4.5,4.5 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,"(3,353 reviews)",Family,Modern,Business,Breakfast included,https://www.tripadvisor.in/Hotel_Review-g29768...,https://static.tacdn.com/img2/brand_refresh_20...
2,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,"3. Country Inn Premier Pacific Resort, Mussoorie",4.4,4.4 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,(297 reviews),Romantic,Trendy,Business,NaN,https://www.tripadvisor.in/Hotel_Review-g29768...,https://static.tacdn.com/img2/brand_refresh_20...
3,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,4. Pride Ashiyana Resort Mussoorie,4.9,4.9 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,(795 reviews),Romantic,Family,Quaint,Breakfast included,https://www.tripadvisor.in/Hotel_Review-g29768...,https://static.tacdn.com/img2/brand_refresh_20...
4,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,"5. Ramada by Wyndham,Mussoorie Mall Road",4.9,4.9 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,"(1,940 reviews)",Romantic,Park View,Classic,Breakfast included,NaN,NaN
5,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,6. Hotel Mussoorie Heights,5.0,5 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,(3 reviews),Quaint,Luxury,NaN,NaN,NaN,NaN
6,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,7. Sterling Mussoorie,4.7,4.7 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,"(3,905 reviews)",Romantic,Trendy,Business,NaN,NaN,NaN
7,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,"8. Sangam By Stotrak, Jhula Ghar Mussoorie",5.0,5 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,(73 reviews),Romantic,Budget,Family,NaN,NaN,NaN
8,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,9. Tulip Inn Green Castle - Hotel & Spa,3.9,3.9 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,(331 reviews),Romantic,Modern,Family,NaN,NaN,NaN
9,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,10. Mosaic Hotel Mussoorie,4.8,4.8 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,"(1,619 reviews)",Romantic,Boutique,Great View,Breakfast included,NaN,NaN
10,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,"11. The Hosteller Mussoorie, Mall Road",4.5,4.5 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,(84 reviews),Romantic,Quaint,Charming,NaN,https://www.tripadvisor.in/Hotel_Review-g29768...,https://static.tacdn.com/img2/brand_refresh_20...
11,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,"12. The Fern Brentwood Resort Mussoorie, Serie...",4.8,4.8 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,"(1,734 reviews)",Romantic,Classic,Trendy,Breakfast included,https://www.tripadvisor.in/Hotel_Review-g29768...,https://static.tacdn.com/img2/brand_refresh_20...
12,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,13. The Palm Aryan Mussoorie - A Boutique Hotel,4.5,4.5 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,(26 reviews),Romantic,Boutique,Family,NaN,NaN,NaN
13,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,14. Madhuban Sarovar Portico Mussoorie,4.8,4.8 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,"(1,234 reviews)",Romantic,City View,Family,NaN,NaN,NaN
14,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,15. Hotel Padmini Nivas,4.5,4.5 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,(824 reviews),Romantic,Park View,Classic,NaN,https://www.tripadvisor.in/Hotel_Review-g29768...,https://static.tacdn.com/img2/brand_refresh_20...
15,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,"16. Lemon Tree Resort, Mussoorie",4.9,4.9 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,(249 reviews),Romantic,Quaint,Business,Breakfast included,NaN,NaN
16,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,17. The Mountain Quail Hotel & Resort,4.7,4.7 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,(533 reviews),Romantic,Trendy,Business,Breakfast included,https://www.tripadvisor.in/Hotel_Review-g29768...,https://static.tacdn.com/img2/brand_refresh_20...
17,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,18. Hotel Sungrace,4.8,4.8 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,"(1,550 reviews)",Romantic,Classic,Trendy,Breakfast included,https://www.tripadvisor.in/Hotel_Review-g29768...,https://static.tacdn.com/img2/brand_refresh_20...
18,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,19. Treebo Raj Mall Road,5.0,5 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,(6 reviews),Budget,Business,Quaint,NaN,NaN,NaN
19,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,"20. The Oasis Mussoorie, a member of Radisson ...",4.7,4.7 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,"(2,393 reviews)",Romantic,Modern,Family,Breakfast included,NaN,NaN
20,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,21. JW Marriott Mussoorie Walnut Grove Resort ...,4.8,4.8 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,"(4,209 reviews)",Romantic,Park View,Trendy,Breakfast included,NaN,NaN
21,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,"22. Hotel Paradise Mansion, Mussoorie",4.4,4.4 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,(380 reviews),Romantic,Trendy,Family,Breakfast included,https://www.tripadvisor.in/Hotel_Review-g29768...,https://static.tacdn.com/img2/brand_refresh_20...
22,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,"23. Welcomhotel By ITC Hotels, The Savoy",4.9,4.9 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,"(5,424 reviews)",Romantic,Park View,Classic,All inclusive,NaN,NaN
23,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,24. Zone Connect By The Park Mussoorie,4.5,4.5 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,(821 reviews),Romantic,Trendy,Modern,NaN,https://www.tripadvisor.in/Hotel_Review-g29768...,https://static.tacdn.com/img2/brand_refresh_20...
24,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,25. Club Mahindra Mussoorie,4.8,4.8 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,"(4,090 reviews)",Romantic,Family,Charming,NaN,NaN,NaN
25,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,26. Fortune Resort Grace - Mussoorie,4.8,4.8 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,"(2,960 reviews)",Romantic,City View,Modern,Breakfast included,NaN,NaN
26,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,27. Mussoorie Gateway,4.1,4.1 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,(464 reviews),Quiet,Trendy,Budget,NaN,NaN,NaN
27,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,"28. Tree of Life Highlands, Landour-Mussoorie",4.7,4.7 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,(201 reviews),Romantic,Quaint,Mid-range,Breakfast included,https://www.tripadvisor.in/Hotel_Review-g29768...,https://static.tacdn.com/img2/brand_refresh_20...
28,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,29. Royal Orchid Fort Resort,4.8,4.8 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,"(3,208 reviews)",Romantic,City View,Modern,NaN,NaN,NaN
29,https://www.tripadvisor.in/Hotel_Review-g29768...,https://dynamic-media-cdn.tripadvisor.com/medi...,30. Hotel Highland By DLS Hotels,4.7,4.7 of 5 bubbles,https://www.tripadvisor.in/Hotel_Review-g29768...,(445 reviews),Romantic,Boutique,Great View,Breakfast included,https://www.tripadvisor.in/Hotel_Review-g29768...,https://static.tacdn.com/img2/brand_refresh_20...

In [7]:
df.isnull()

,BMQDV href,NhWcC src,biGQs,biGQs 2,evwcZ,BMQDV href 3,biGQs 3,AVYYu,AVYYu 2,AVYYu 3,AVYYu 4,BMQDV href 4,TPuys src
0,False,False,False,False,False,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,True
5,False,False,False,False,False,False,False,False,False,True,True,True,True
6,False,False,False,False,False,False,False,False,False,False,True,True,True
7,False,False,False,False,False,False,False,False,False,False,True,True,True
8,False,False,False,False,False,False,False,False,False,False,True,True,True
9,False,False,False,False,False,False,False,False,False,False,False,True,True
10,False,False,False,False,False,False,False,False,False,False,True,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,True,True,True
13,False,False,False,False,False,False,False,False,False,False,True,True,True
14,False,False,False,False,False,False,False,False,False,False,True,False,False
15,False,False,False,False,False,False,False,False,False,False,False,True,True
16,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,True,True,True
19,False,False,False,False,False,False,False,False,False,False,False,True,True
20,False,False,False,False,False,False,False,False,False,False,False,True,True
21,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,True,True
23,False,False,False,False,False,False,False,False,False,False,True,False,False
24,False,False,False,False,False,False,False,False,False,False,True,True,True
25,False,False,False,False,False,False,False,False,False,False,False,True,True
26,False,False,False,False,False,False,False,False,False,False,True,True,True
27,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,True,True,True
29,False,False,False,False,False,False,False,False,False,False,False,False,False